directories:
  output: release
  buildResources: build
appId: com.levisilvino.calculadora-freelance
productName: Calculadora de Preço por Trabalho
files:
  - filter:
      - dist/**/*
      - main.js
      - package.json
extraResources:
  - from: dist
    to: dist
    filter:
      - '**/*'
electronVersion: 28.3.3
